name: arion_coder

services:
  # PHP-FPM (Laravel)
  app:
    environment:
      APP_ROLE: app
      RUN_MIGRATIONS: "true"
    build:
      context: ./api
      dockerfile: .docker/Dockerfile.php
    container_name: app
    depends_on:
      - db
      - redis
    env_file:
      - ./api/.env
    volumes:
      - ./api:/var/www/html
      - ./api/storage:/var/www/html/storage
    networks:
      - appnet

  reverb:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile.php
    container_name: reverb
    depends_on:
      - app
      - redis
    env_file:
      - ./api/.env
    volumes:
      - ./api:/var/www/html
    ports:
      - "${REVERB_PORT:-8081}:${LOCAL_PORT:-8080}"
    networks:
      - appnet


  # Queues (queue:work)
  queue:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile.php
    container_name: queue
    restart: on-failure
    environment:
      APP_ROLE: queue
      RUN_MIGRATIONS: "false"
    depends_on:
      - app
      - redis
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./api:/var/www/html
      - ./api/storage:/var/www/html/storage
    networks:
      - appnet

  # Planner
  scheduler:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile.php
    container_name: scheduler
    environment:
      APP_ROLE: scheduler
      RUN_MIGRATIONS: "false"
    restart: on-failure
    depends_on:
      - app
      - db
      - redis
    env_file:
      - ./api/.env
    volumes:
      - ./api:/var/www/html
      - ./api/storage:/var/www/html/storage
    networks:
      - appnet

  # Nginx (API + static files /api/public)
  web:
    image: nginx:1.27-alpine
    container_name: web
    env_file:
      - ./api/.env
    depends_on:
      - app
    ports:
      - "${LOCAL_PORT:-8080}:80"
    volumes:
      - ./api:/var/www/html
      - ./api/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    env_file:
      - ./api/.env
    ports:
      - "${LOCAL_REDIS_PORT:-6379}:6379"
    networks:
      - appnet

  # MySQL 8
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - ./api/.env
    ports:
      - "${LOCAL_DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-app}
      MYSQL_PASSWORD: ${DB_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-app}
    volumes:
      - db-data:/var/lib/mysql
    command: [
      "mysqld",
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    networks:
      - appnet

volumes:
  app-vendor:
  app-storage:
  db-data:

networks:
  appnet:
    driver: bridge
